### ISSUE TITLE
for discussion: snafu packages when xmlresolution can't retrieve schemas?

### ISSUE THREAD

**Issue by lydiam** [fcla/xmlresolution#20]
For future discussion:

Carol suggested that perhaps xmlresolution should snafu a package if it can't retrieve any schemas.  We currently have a lot of packages with empty xmlresolution tarballs and manifests like the following:

```
 <resolutions collection="E1GZGPT0I_BFRWND"><resolution time="2012-02-21T13:14:55-05:00" md5="19756d4e91e3e41879797b3e588bb6f1" name="file://fclnx30.fcla.edu/E1GZGPT0I_BFRWND/AA00009102_00001.mets">
 <schema status="failure" message="Connection refused - connect(2)" location="http://digital.uflib.ufl.edu/metadata/sobekcm/sobekcm.xsd" namespace="http://digital.uflib.ufl.edu/metadata/sobekcm/"/>
 <schema status="failure" message="Connection refused - connect(2)" location="http://www.loc.gov/mods/v3/mods-3-4.xsd" namespace="http://www.loc.gov/mods/v3"/><schema status="failure" message="Connection refused - connect(2)" location="http://www.loc.gov/standards/mets/mets.xsd" namespace="http://www.loc.gov/METS/"/>
 <schema status="unresolved" namespace="http://www.w3.org/1999/xlink"/></resolution><resolution time="2012-02-21T13:14:55-05:00" md5="992b8261c17da0c312d09e1228e8c0cc" name="file://fclnx30.fcla.edu/E1GZGPT0I_BFRWND/AA00009102_00001.xml">
 <schema status="failure" message="Connection refused - connect(2)" location="http://digital.uflib.ufl.edu/metadata/sobekcm/sobekcm.xsd" namespace="http://digital.uflib.ufl.edu/metadata/sobekcm/"/>
 <schema status="failure" message="Connection refused - connect(2)" location="http://www.fcla.edu/dls/md/daitss/daitss.xsd" namespace="http://www.fcla.edu/dls/md/daitss/"/>
 <schema status="failure" message="Connection refused - connect(2)" location="http://www.loc.gov/mods/v3/mods-3-4.xsd" namespace="http://www.loc.gov/mods/v3"/>
 <schema status="failure" message="Connection refused - connect(2)" location="http://www.loc.gov/standards/mets/mets.xsd" namespace="http://www.loc.gov/METS/"/>
 <schema status="unresolved" namespace="http://www.w3.org/1999/xlink"/></resolution></resolutions>
```

We don't want to have to reprocess the entire package in order to obtain the schemas.  In this case there clearly was some sort of problem with xmlresolution.

**Comment by cchou** [comment]
I am wondering what's the best way to detect whether it's configuration related or bad schema entry in the xml.  I wonder if filter out "Connection refused" in xml resolution can serve the purpose.  If so, we can 5XX on the "Connection refused" message and snafu.

**Comment by cchou** [comment]
Carol recommends that this issue be addressed in lieu of #7, because #7 is not specific.

We don't want to SNAFU if occasionally a schema is unreachable.  We want to SNAFU when there's some sort of major problem:
- if Squid is down core should currently SNAFU and we want it to SNAFU. (doesn't currently SNAFU)

Other possible cases, to be tested and discussed:
- question:  will Squid delete a cached schema before it retrieves a new version?  Under D1 there was a situation where webcache was being refreshed and deleted schemas, but loc.gov was down and a new version wasn't retrieved, and consequently a large number of AIPs were missing loc.gov schemas.  Would this happen under Squid?  This could be a serious situation that could warrant a SNAFU. (Because we refresh Squid on Wednesdays and LOC schedules downtime for weekends and holidays this may not happen.)

**Comment by cchou** [comment]
To do:
1.  No http_status tags in premis.xml, but could get put into the manifest.xml and the log.
2. http return codes should go to core.

**Comment by cchou** [comment]
Moved Ira's comment from #7 here, 
"

Instead of passing the http_code back in the premis.xml XMLRESOLUTIOn will now return http_code 503 to the calling client when xmlresolution gets 'Connection refused - connect(2)' when trying to contact squid. All other http code that squid receives will be passed back as http_code 201.

If XMLRESOLUTION is configured not to talk to squid proxy but is going directly to the Internet
it will never receive 'Connection refused - connect(2)' but should receive http like return such as 503 when the web site is down or a 404 - Not Found when asking fro a non-existent object. This assures us that that the client to XMLRESOLUTION will receive a 503 only when squid is down.

http_code will not be returned in premis.xml but expect StartTag: invalid element name
to be seen. This has not changed as seen in the following snippet returned for a poorly formed xml.

URI
file://marsala.fcla.edu/xmlresolution/events/052de0ef3fd66627dcb091db1e530b1d-ce31f4

XML Resolution
2012-07-31T15:33:37-04:00

error

StartTag: invalid element name
"

**Comment by iterman** [comment]
If our resolver proxy is down  or not providing its functionality the result will be snafu'ed packages. 
However, if XMLResolution cannot resolve an object this will not result in a snafu'ed package.
 post.rb was modified to return the correct status to core.

**Comment by lydiam** [comment]
I'm not sure what the "correct status" is supposed to be or how to test this.

**Comment by iterman** [comment]
On 11/6/12 3:53 PM, Lydia Motyka wrote:

> I'm not sure what the "correct status" is supposed to be or how to 
> test this.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daitss/xmlresolution/issues/20#issuecomment-10127280. 
> 
> Lydia,

We have exhaustively tested the situation of "normal" failures i.e.
unresolved dtd's, schemas, and stylesheets.

You are probably wondering how to test the "503" squid down errors.
I accomplished this in two ways:
1.  I brought down my development copy of squid
2.  I doctored my daitss config file to point to a non-existent resolver 
proxy.

Ira.

**Comment by lydiam** [comment]
I've seen 404 and 503 error messages in the manifest.xml files in various cases, presumably with squid running on the ripple server, but I'm not sure if those are correct in this context.  

Examples:
TestCase18:

```
 <dtd status="failure" location="http://nonexistent.server.fcla.edu/rss-0.91.dtd" message="503 "Service Unavailable""/>

 When I enter the location in my browser I get a "Not Found" error.  Is the 503 result correct in this case?
```

TestCase21:

```
 <stylesheet message="404 "Not Found"" location="http://schema.fcla.edu/xml/this_stylesheet-doesnot-exist.xsl" status="failure"/>

 When I enter the location in my browser I get a "Not Found" error.  The 404 error in the manifest appears to be correct in this case.  Can you confirm?
```

**Comment by lydiam** [comment]
I retested TestCase18 just now and still get a 503.  Ira says that the 503 should only happen if squid is down.  

From the most recent manifest.xml file (see timestamp):

```
 <resolution md5="943e13e038ed03a463f5b6ddcec5186e" name="file://ripple.fcla.edu/EGX6LJZHD_4NUFWD/public-dtd-points-nonexist-server.xml" time="2012-11-06T17:13:21-05:00">
<dtd status="failure" location="http://nonexistent.server.fcla.edu/rss-0.91.dtd" message="503 &quot;Service Unavailable&quot;"/>
</resolution>
```

**Comment by iterman** [comment]
I believe XMLResolution is behaving correctly.

The 503 when squid is down is different from the 503 when referring to a fake server.

I reran TestCase18 in a development environment where I have more control i.e.  I can bring squid up/down and also modify the DAITSS config file.

In Case 1, below, the 503 is just indicating the service thru squid was unavailable, server name is nonexistent.server.fcla.edu  which is bogus.  Except for the bogus http://nonexistent.server.fcla.edu/rss-0.91.dtd
the rest of schemas got downloaded.

In case 2, below, squid was down, and xmlresolution told core via a rc=503 that the package should not ingest.
In the future we would be alerted that squid is down because no package would ingest.
1. I ran TestCase18 when squid was functioning - result: package archived.  Here is the complete manifest file
   <?xml version="1.0" encoding="UTF-8"?>
   <resolutions collection="EEIFOJ82S_JOMT7U">
   <resolution name="file://localhost.ufl.edu/EEIFOJ82S_JOMT7U/public-dtd-points-nonexist-server.xml" md5="243e2341a1c274d69951d32ebe05cfd8" time="2012-11-07T09:58:39-05:00">
     <dtd status="failure" message="503 &quot;Service Unavailable&quot;" location="http://nonexistent.server.fcla.edu/rss-0.91.dtd"/>
   </resolution>
   <resolution name="file://localhost.ufl.edu/EEIFOJ82S_JOMT7U/TestCase18.xml" md5="253318f9b287485928890a99a7238fe1" time="2012-11-07T09:58:38-05:00">
     <schema status="success" location="http://dublincore.org/schemas/xmls/simpledc20021212.xsd" namespace="http://purl.org/dc/elements/1.1/" md5="d90774b02fa694f3b358b4ed828295be" last_modified="2012-11-07T09:58:38-05:00"/>
     <schema status="success" location="http://www.fcla.edu/dls/md/daitss/daitss.xsd" namespace="http://www.fcla.edu/dls/md/daitss/" md5="2b2f6040cfc603d5873d7fa0bf976274" last_modified="2012-05-30T14:05:46-04:00"/>
     <schema status="success" location="http://www.loc.gov/standards/mets/mets.xsd" namespace="http://www.loc.gov/METS/" md5="42519c72a741cc30e256b99369f1d735" last_modified="2012-03-05T12:02:18-05:00"/>
     <schema status="success" location="http://www.loc.gov/standards/xlink/xlink.xsd" namespace="http://www.w3.org/1999/xlink" md5="01490ebdea13c1bc82a17e4783daeeaa" last_modified="2007-08-23T15:02:01-04:00"/>
     <schema status="success" location="http://www.w3.org/2001/03/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace" md5="712fc5a7750e69f904f61086a997713c" last_modified="2004-03-31T12:57:18-05:00"/>
     <schema status="success" location="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace" md5="5e0bd6f94ec78a3a88fca2275ab05f9e" last_modified="2009-01-21T17:06:40-05:00"/>
     <schema status="success" location="http://www.w3.org/2001/XMLSchema.xsd" namespace="http://www.w3.org/2001/XMLSchema" md5="1fadeaf88d4b93ab263f7c59917c26bc" last_modified="2004-03-20T07:53:09-05:00"/>
   </resolution>
   </resolutions>

what squid is passing back:

curl -I http://nonexistent.server.fcla.edu/rss-0.91.dtd
HTTP/1.0 503 Service Unavailable
Server: squid/3.1.19
Mime-Version: 1.0
Date: Wed, 07 Nov 2012 15:22:53 GMT
Content-Type: text/html
Content-Length: 3607
X-Squid-Error: ERR_DNS_FAIL 0
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from iterman.fcla.edu
Via: 1.0 iterman.fcla.edu (squid/3.1.19)
Connection: keep-alive
1.  I ran TestCase18 when squid was down - result: Ingest Error as expected.
   XMLResolution passed back to core a retrun code 503.  Here is the result in the gui TestCase18/EPY7R4O26_TKD0HS : ingesting (error)  

bad status: 503 -- <?xml version="1.0" encoding="UTF-8"?>
<premis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/premis.xsd" version="2.1">
  <object xsi:type="file">
    <objectIdentifier>
      <objectIdentifierType>URI</objectIdentifierType>
      <objectIdentifierValue>file://localhost.ufl.edu/EPY7R4O26_TKD0HS/TestCase18.xml</objectIdentifierValue>
    </objectIdentifier>
    <objectCharacteristics>
      <compositionLevel>0</compositionLevel>
      <fixity>
        <messageDigestAlgorithm>MD5</messageDigestAlgorithm>
        <messageDigest>4c6b9b6527e1f87da3cb217e690171f6</messageDigest>
      </fixity>
      <size>2520</size>
      <format>
        <formatDesignation>
          <formatName>XML</formatName>
          <formatVersion>1.0</formatVersion>
        </formatDesignation>
        <formatRegistry>
          <formatRegistryName>http://www.nationalarchives.gov.uk/pronom</formatRegistryName>
          <formatRegistryKey>fmt/101</formatRegistryKey>
        </formatRegistry>
      </format>
    </objectCharacteristics>
    <linkingEventIdentifier>
      <linkingEventIdentifierType>URI</linkingEventIdentifierType>
      <linkingEventIdentifierValue>file://iterman.fcla.edu/xmlresolution/events/4c6b9b6527e1f87da3cb217e690171f6-329a36</linkingEventIdentifierValue>
    </linkingEventIdentifier>
  </object>
  <event>
    <eventIdentifier>
      <eventIdentifierType>URI</eventIdentifierType>
      <eventIdentifierValue>file://iterman.fcla.edu/xmlresolution/events/4c6b9b6527e1f87da3cb217e690171f6-329a36</eventIdentifierValue>
    </eventIdentifier>
    <eventType>XML Resolution</eventType>
    <eventDateTime>2012-11-07T09:52:50-05:00</eventDateTime>
    <eventOutcomeInformation>
      <eventOutcome>failure</eventOutcome>
      <eventOutcomeDetail>
        <eventOutcomeDetailExtension>
          <broken_link type="schema">http://dublincore.org/schemas/xmls/simpledc20021212.xsd</broken_link>
          <broken_link type="schema">http://www.fcla.edu/dls/md/daitss/daitss.xsd</broken_link>
          <broken_link type="schema">http://www.loc.gov/standards/mets/mets.xsd</broken_link>
          <broken_link type="unresolvable">http://www.w3.org/1999/xlink</broken_link>
        </eventOutcomeDetailExtension>
      </eventOutcomeDetail>
    </eventOutcomeInformation>
    <linkingAgentIdentifier>
      <linkingAgentIdentifierType>URI</linkingAgentIdentifierType>
      <linkingAgentIdentifierValue>info:fcla/daitss/xmlresolution/1.4.2</linkingAgentIdentifierValue>
    </linkingAgentIdentifier>
    <linkingObjectIdentifier>
      <linkingObjectIdentifierType>URI</linkingObjectIdentifierType>
      <linkingObjectIdentifierValue>file://localhost.ufl.edu/EPY7R4O26_TKD0HS/TestCase18.xml</linkingObjectIdentifierValue>
    </linkingObjectIdentifier>
  </event>
  <agent>
    <agentIdentifier>
      <agentIdentifierType>URI</agentIdentifierType>
      <agentIdentifierValue>info:fcla/daitss/xmlresolution/1.4.2</agentIdentifierValue>
    </agentIdentifier>
    <agentName>XML Resolution Service</agentName>
    <agentType>Web Service</agentType>
    <agentNote>XMLResolution Version 1.4.2, Git Revision Unknown, Capistrano Release Not Available</agentNote>
  </agent>
</premis>
http://localhost:7004/ieids/EPY7R4O26_TKD0HS/: 503
<?xml version="1.0" encoding="UTF-8"?>
<premis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/premis.xsd" version="2.1">
  <object xsi:type="file">
    <objectIdentifier>
      <objectIdentifierType>URI</objectIdentifierType>
      <objectIdentifierValue>file://localhost.ufl.edu/EPY7R4O26_TKD0HS/TestCase18.xml</objectIdentifierValue>
    </objectIdentifier>
    <objectCharacteristics>
      <compositionLevel>0</compositionLevel>
      <fixity>
        <messageDigestAlgorithm>MD5</messageDigestAlgorithm>
        <messageDigest>4c6b9b6527e1f87da3cb217e690171f6</messageDigest>
      </fixity>
      <size>2520</size>
      <format>
        <formatDesignation>
          <formatName>XML</formatName>
          <formatVersion>1.0</formatVersion>
        </formatDesignation>
        <formatRegistry>
          <formatRegistryName>http://www.nationalarchives.gov.uk/pronom</formatRegistryName>
          <formatRegistryKey>fmt/101</formatRegistryKey>
        </formatRegistry>
      </format>
    </objectCharacteristics>
    <linkingEventIdentifier>
      <linkingEventIdentifierType>URI</linkingEventIdentifierType>
      <linkingEventIdentifierValue>file://iterman.fcla.edu/xmlresolution/events/4c6b9b6527e1f87da3cb217e690171f6-329a36</linkingEventIdentifierValue>
    </linkingEventIdentifier>
  </object>
  <event>
    <eventIdentifier>
      <eventIdentifierType>URI</eventIdentifierType>
      <eventIdentifierValue>file://iterman.fcla.edu/xmlresolution/events/4c6b9b6527e1f87da3cb217e690171f6-329a36</eventIdentifierValue>
    </eventIdentifier>
    <eventType>XML Resolution</eventType>
    <eventDateTime>2012-11-07T09:52:50-05:00</eventDateTime>
    <eventOutcomeInformation>
      <eventOutcome>failure</eventOutcome>
      <eventOutcomeDetail>
        <eventOutcomeDetailExtension>
          <broken_link type="schema">http://dublincore.org/schemas/xmls/simpledc20021212.xsd</broken_link>
          <broken_link type="schema">http://www.fcla.edu/dls/md/daitss/daitss.xsd</broken_link>
          <broken_link type="schema">http://www.loc.gov/standards/mets/mets.xsd</broken_link>
          <broken_link type="unresolvable">http://www.w3.org/1999/xlink</broken_link>
        </eventOutcomeDetailExtension>
      </eventOutcomeDetail>
    </eventOutcomeInformation>
    <linkingAgentIdentifier>
      <linkingAgentIdentifierType>URI</linkingAgentIdentifierType>
      <linkingAgentIdentifierValue>info:fcla/daitss/xmlresolution/1.4.2</linkingAgentIdentifierValue>
    </linkingAgentIdentifier>
    <linkingObjectIdentifier>
      <linkingObjectIdentifierType>URI</linkingObjectIdentifierType>
      <linkingObjectIdentifierValue>file://localhost.ufl.edu/EPY7R4O26_TKD0HS/TestCase18.xml</linkingObjectIdentifierValue>
    </linkingObjectIdentifier>
  </event>
  <agent>
    <agentIdentifier>
      <agentIdentifierType>URI</agentIdentifierType>
      <agentIdentifierValue>info:fcla/daitss/xmlresolution/1.4.2</agentIdentifierValue>
    </agentIdentifier>
    <agentName>XML Resolution Service</agentName>
    <agentType>Web Service</agentType>
    <agentNote>XMLResolution Version 1.4.2, Git Revision Unknown, Capistrano Release Not Available</agentNote>
  </agent>
</premis>

**Comment by lydiam** [comment]
TestCase18 results have been consistent ever since I was provided with the test SIP Oct. 15, so if the expected result is an archived package with a 503 in the manifest and broken_link for http://nonexistent.server.fcla.edu/rss-0.91.dtd then the issue can be closed.
