### ISSUE TITLE
collection from one xml resolution process was deleted by another xml resolution process

### ISSUE THREAD

**Issue by cchou** [fcla/xmlresolution#33]
While testing dissemination, we ran into a weird situation where the collection created by one xmlresolution process was deleted by another xmlresolution process, causing dissemination snafu.

  bad status
  http://xmlresolution.ripple.fcla.edu/ieids/EFCVYP5T6_0IEJJQ: 500
  500 Internal Service Error - The directory for storing the collections, '/var/daitss/tmp/d20121130-19152-1egoeov/collections',     doesn't exist or is unreadable by this user (daitss) and group (daitss).

Upon reviewing the log, it appears that process 19159 delete the collection created by process 19155.

  2012 Nov 30 14:17:26 ripple XmlResolution[19155]:  INFO xmlresolution.ripple.fcla.edu: Retrieved   http://www.w3.org/2001/XMLSchema.xsd for document file://ripple.fcla.edu/EFCVYP5T6_0IEJJQ/amj9816.xml, namespace http://www.w3.org/2001/XMLSchema. 128.227.228.33 - - "POST /ieids/EFCVYP5T6_0IEJJQ/ HTTP/1.1"
  2012 Nov 30 14:17:26 ripple XmlResolution[19155]:  INFO xmlresolution.ripple.fcla.edu: Rack: 128.227.228.33 - - [30/Nov/2012 14:17:26] "POST /ieids/EFCVYP5T6_0IEJJQ/ " 201 2813 0.5782
  2012 Nov 30 14:17:26 ripple XmlResolution[19155]:  INFO xmlresolution.ripple.fcla.edu: Rack: 128.227.228.33 - - [30/Nov/2012 14:17:26] "GET /ieids/EFCVYP5T6_0IEJJQ/ " 200 238592 0.0184
  2012 Nov 30 14:21:26 ripple XmlResolution[19159]:  INFO xmlresolution.ripple.fcla.edu: Temporary directory /var/daitss/tmp/d20121130-19152-1egoeov deleted
  2012 Nov 30 14:21:26 ripple XmlResolution[19159]:  INFO xmlresolution.ripple.fcla.edu: Ending XMLResolution Version 1.4.2, Git Revision 4d6b12f824c5b0489c818b26ecbdc78a3121d82c, Capistrano Release 20121120191144

Resetting and rerun the package didn't help.  We then restart daitss but it still snafu.  However, 2nd restart did eventually allow the package to complete xmlresolution.  

Here are the links to the packages,
https://core.ripple.fcla.edu/package/EFCVYP5T6_0IEJJQ

https://core.ripple.fcla.edu/package/EXCKED2LL_H7KQ8W

**Comment by cchou** [comment]
This happen again,

http://xmlresolution.ripple.fcla.edu/ieids/EWHX2UNWF_73JK77: 500
500 Internal Service Error - The directory for storing the collections, '/var/daitss/tmp/d20130130-19377-18vks9c/collections', doesn't exist or is unreadable by this user (daitss) and group (daitss).

Here is the xmlresolution log.

Looks like process 19380 tries deleted the cache created by process 19377.

2013 Jan 30 13:31:52 ripple XmlResolution[19377]:  INFO xmlresolution.ripple.fcla.edu: Initializing with temp data directory /var/daitss/tmp/d20130130-19377-18vks9c; caching proxy is localhost:3128
2013 Jan 30 13:31:52 ripple XmlResolution[19377]:  INFO xmlresolution.ripple.fcla.edu: Collections directory /var/daitss/tmp/d20130130-19377-18vks9c/collections created
2013 Jan 30 13:31:52 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Retrieved http://www.loc.gov/standards/xlink/xlink.xsd for document file://flash.fcla.edu/E99E5OEHL_MO6E16/ateam-bad-pdf.xml, namespace http://www.w3.org/1999/xlink. 128.227.228.235 - - "POST /ieids/E99E5OEHL_MO6E16/ HTTP/1.1"
2013 Jan 30 13:31:52 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Retrieved http://www.w3.org/2001/xml.xsd for document file://flash.fcla.edu/E99E5OEHL_MO6E16/ateam-bad-pdf.xml, namespace http://www.w3.org/XML/1998/namespace. 128.227.228.235 - - "POST /ieids/E99E5OEHL_MO6E16/ HTTP/1.1"
2013 Jan 30 13:31:52 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Retrieved http://www.w3.org/2001/XMLSchema.xsd for document file://flash.fcla.edu/E99E5OEHL_MO6E16/ateam-bad-pdf.xml, namespace http://www.w3.org/2001/XMLSchema. 128.227.228.235 - - "POST /ieids/E99E5OEHL_MO6E16/ HTTP/1.1"
2013 Jan 30 13:31:52 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Rack: 128.227.228.235 - - [30/Jan/2013 13:31:52] "POST /ieids/E99E5OEHL_MO6E16/ " 201 2823 0.1305
2013 Jan 30 13:31:52 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Rack: 128.227.228.235 - - [30/Jan/2013 13:31:52] "GET /ieids/E99E5OEHL_MO6E16/ " 200 294400 0.0371
2013 Jan 30 13:34:35 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Temporary directory /var/daitss/tmp/d20130130-19377-18vks9c deleted
2013 Jan 30 13:34:35 ripple XmlResolution[19380]:  INFO xmlresolution.ripple.fcla.edu: Ending XMLResolution Version 1.4.2, Git Revision 4d6b12f824c5b0489c818b26ecbdc78a3121d82c, Capistrano Release 20121120191144
2013 Jan 30 13:34:39 ripple XmlResolution[19742]: ERROR xmlresolution.ripple.fcla.edu: 500 Internal Service Error - The directory for storing the collections, '/var/daitss/tmp/d20130130-19377-18vks9c/collections', doesn't exist or is unreadable by this user (daitss) and group (daitss). 128.227.228.33 - - "PUT /ieids/E3CLVSE0J_KWGYUL HTTP/1.1"
2013 Jan 30 13:34:39 ripple XmlResolution[19742]:  INFO xmlresolution.ripple.fcla.edu: Rack: 128.227.228.33 - - [30/Jan/2013 13:34:39] "PUT /ieids/E3CLVSE0J_KWGYUL " 500 199 0.0311
2013 Jan 30 13:35:45 ripple XmlResolution[19742]: ERROR xmlresolution.ripple.fcla.edu: 500 Internal Service Error - The directory for storing the collections, '/var/daitss/tmp/d20130130-19377-18vks9c/collections', doesn't exist or is unreadable by this user (daitss) and group (daitss). 128.227.228.33 - - "PUT /ieids/ECXU4T8NY_54K23C HTTP/1.1"
2013 Jan 30 13:35:45 ripple XmlResolution[19742]:  INFO xmlresolut

**Comment by childree** [comment]
I think this is because services were stopped and started out from under 
this process.  I just reset everything in the workspace and I have had 
successes.

**Comment by cchou** [comment]
To have one process delete the cache created by another process, that violates the stateless principle.  Not good design.

**Comment by iterman** [comment]
XMLResolution at startup creates a temporary directory using ruby 'Dir.mktmpdir' .  This creates a temporary directory with a name something like /var/daitss/tmp/d20130130-19377-18vks9c.  Then using Ruby Dir.mkdir it creates two temp directories under this one called 'schema" the other called 'collections'.  At shutdown of XMLResolution - normal or otherwise a Ruby shutdown hook deletes the directory it created with  "Dir.mktmpdir' by using Ruby 'FileUtils.rm_rf'.  This mode of operation was introduced as a result of issue #17.  

 XMLResolution used to keep schemas permenently in the schemas directory and collections for at least 24 hours in the collections directory.  These directories were in  the Xmlresolution  "releases" directory.  The fix for #17 changed  this behavior.

XMLResolution is not stateless. Multiple POST requests build up a collection.  The final request a 'GET' is for all the posts and results in tar file that may have many web objects from different post requests.

In an environment where several instances of XMLResolution processes exist there can arise a situation where say process A creates a collection it's knowledge of it directories is distinct from XMLResolution process B.  When process B is dispatched (for instance by phusion) to handle A's request  a problem occurs.  This scenario while not common it happens  in production when there is heavy XMLResolution traffic.  On ripple even less often,  on development never.

One solution to this problem is to revert back to the old way.  XMLResolution should store it schemas and and collections in a directory in  that is permanent.   The directories should not be deleted at shutdown.  The number of files and number of bytes is not inordinately high.  

A second solution would involve a very significant change to XMLResoluton  and Core.  This change is to make XMLResolution stateless. The three step process PUT,  multiple POSTS, and the final GET
would need to be replaced by multiple single requests.

I don't think were going to seem many 501 errors in production but they probably will occur when XMLResolution traffic is heavy.

**Comment by cchou** [comment]
However, the above description does not address why the temp directory created by one process, say process A, were deleted by process B when process B is shutting down?  Isn't process B should only delete the temp directly created by itself?

Reverting to the old way of xml resolution would bring the problem back where schama caches were built in the code directory and were never cleaned up, ending up lots of cruft in our production server.

**Comment by iterman** [comment]
Modified xmlresolution.conf to PassengerSpawnMethod conservative.

I believe the problem is fixed.

**Comment by iterman** [comment]
The foregoing change was applied to ripple only.  

The prior value of PassengerSpawnMethod was left blank so it defaulted to
 smart-lv2.  
A quote from the Phusion Passenger User's Guide (even though) it refers to rail it is appropriate for just ruby)
"When the smart spawn method is being used, Phusion Passenger will first create a so-called ApplicationSpawner server process. This process loads the entire Rails application along with the Rails framework, by loading environment.rb. Then, whenever Phusion Passenger needs a new worker process, it will instruct the ApplicationSpawner server to do so. The ApplicationSpawner server will create a worker new process that reuses the already loaded Rails application/framework. Creating a worker process through an already running ApplicationSpawner server is very fast, about 10 times faster than loading the Rails application/framework from scratch. If the Ruby interpreter is copy-on-write friendly (that is, if you’re running Ruby Enterprise Edition) then all created worker processes will share as much common memory as possible. That is, they will all share the same application and Rails framework code."     and  "The smart method allows different worker processes that belong to the same application to share memory."

What probably was happening was the temporary directory from process A was known to process B for it was kept in a global variable and then later on in an instance variable.
