### ISSUE TITLE
Distinquish failure connecting to proxy server from merely unreachable schemas

### ISSUE THREAD

**Issue by grf** [fcla/xmlresolution#7]
## Description

Currently, it's not an error to be unable to retrieve a schema.
When we analyze an XML document by sending it to the xml
resolution service, we get returned a PREMIS fragment document, 
and the overall eventOutcome may be failure, success, or mixed.   

Trouble is,  if we are unable to contact the proxy server (say
it's not turned on) we don't distinguish from acceptable,
unreachable schemas - this is a limitation of how Net::HTTP
is being used.
## Task

Fix that so we can fail with server error for this kind of configuration
issue,  passing along a cogent error message to ingest.
Perhaps we ping proxy, looking for a connection refused and return a configuration exception?

**Comment by iterman** [comment]
The premis xml returned to core from the POST request will now include the returned http_status_code  e.g.  <http_status_code>Connection refused - connect(2)</http_status_code>  as one of the tags under <eventOutcomeDetailExtension> tag.

**Comment by cchou** [comment]
Lydia's comment: Since this will be going into the AIP descriptor we should probably discuss this. Doesn't this appear in manifest.xml?  Lydia to provide an example.

**Comment by iterman** [comment]
Instead of passing the http_code back in the premis.xml  XMLRESOLUTIOn will now return  http_code  503 to the calling client when xmlresolution gets 'Connection refused - connect(2)'  when trying to contact squid.  All other http code that squid receives will be passed back as http_code 201.  
 If XMLRESOLUTION is configured not to talk to squid proxy but is going directly to the Internet
it will never receive   'Connection refused - connect(2)'  but should receive http like return such as 503 when the web site is down or a 404 - Not Found when asking fro a non-existent object.  This assures us that that the client to XMLRESOLUTION will receive a 503 only when squid is down.

http_code will not be returned in premis.xml  but expect <error>StartTag: invalid element name</error>
to be seen.  This has not changed as seen in the following snippet returned for a poorly formed xml.

<event>
    <eventIdentifier>
      <eventIdentifierType>URI</eventIdentifierType>
      <eventIdentifierValue>file://marsala.fcla.edu/xmlresolution/events/052de0ef3fd66627dcb091db1e530b1d-ce31f4</eventIdentifierValue>
    </eventIdentifier>
    <eventType>XML Resolution</eventType>
    <eventDateTime>2012-07-31T15:33:37-04:00</eventDateTime>
    <eventOutcomeInformation>
      <eventOutcome>error</eventOutcome>
      <eventOutcomeDetail>
        <eventOutcomeDetailExtension>
          <error>StartTag: invalid element name</error>
        </eventOutcomeDetailExtension>
      </eventOutcomeDetail>
    </eventOutcomeInformation>

**Comment by grf** [comment]
That sounds like a good check - it's what I would do, 503 seems appropriate.

On Tue, Jul 31, 2012 at 4:35 PM, iterman <
reply@reply.github.com

> wrote:
> 
> Instead of passing the http_code back in the premis.xml  XMLRESOLUTIOn
> will now return  http_code  503 to the calling client when xmlresolution
> gets 'Connection refused - connect(2)'  when trying to contact squid.  All
> other http code that squid receives will be passed back as http_code 201.
>  If XMLRESOLUTION is configured not to talk to squid proxy but is going
> directly to the Internet
> it will never receive   'Connection refused - connect(2)'  but should
> receive http like return such as 503 when the web site is down or a 404 -
> Not Found when asking fro a non-existent object.  This assures us that that
> the client to XMLRESOLUTION will receive a 503 only when squid is down.
> 
> http_code will not be returned in premis.xml  but expect <error>StartTag:
> invalid element name</error>
> to be seen.  This has not changed as seen in the following snippet
> returned for a poorly formed xml.

**Comment by cchou** [comment]
The discussion has been moved to #20.  Closing.
